home/urls.py
from django.urls import path
from . import views
from .views import MatkulView, MatkulDetailView, MatkulDeleteView

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('project', views.project, name='project'),
    path('matkul_create', views.Matkul_create_view, name='matkul_create'),
    path('list', MatkulView.as_view(), name='list'),
    path('detail/<int:pk>', MatkulDetailView.as_view(), name='detail'),
    path('detail/<int:pk>/delete', MatkulDeleteView.as_view(), name='delete'),
]

my_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls'))
]

home/models.py
from django.db import models

# Create your models here.
class Matkul(models.Model):
    NamaMatkul = models.CharField(max_length=50)
    Dosen = models.CharField(max_length=50)
    sks = models.IntegerField(blank=True, null=True)
    deskripsi = models.CharField(max_length=100)
    smst = models.CharField(max_length=15)
    kelas = models.CharField(max_length=50)

home/forms.py
from django import forms

from .models import Matkul

class MatkulForm(forms.ModelForm):
    class Meta:
        model = Matkul
        fields = [
            'NamaMatkul',
            'Dosen',
            'sks',
            'deskripsi',
            'smst',
            'kelas'
        ]

home/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, DeleteView
from .forms import MatkulForm
from .models import Matkul
from django.urls import reverse_lazy

# Create your views here.

def index(request):
    return render(request, 'home/index.html')

def about(request):
    return render(request, 'home/about.html')

def project(request):
    return render(request, 'home/project.html')

class MatkulView(ListView):
    model = Matkul
    template_name = 'home/list.html'

class MatkulDetailView(DetailView):
    model = Matkul
    template_name = 'home/detail.html'

class MatkulDeleteView(DeleteView):
    model = Matkul
    template_name = 'home/delete.html'
    success_url = reverse_lazy('home:list')

def Matkul_create_view(request):
    form = MatkulForm(request.POST or None)
    if form.is_valid():
        form.save()
        form = MatkulForm()
    context = {
        "form": form
    }
    return render(request, 'home/matkul_create.html', context)

def Matkul_detail_view(request):
    obj = Matkul.objects.get(id=1)
    context = {
        'object': obj
    }
    return render(request, 'home/matkul_create.html', context)

home/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    {% block meta %}
    {% endblock meta %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}">
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
</head>

<body>
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">BC</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    {% if request.get_full_path == "/" %}
                    <li class="active"><a href="/">Home</a></li>
                    <li><a href="about">About Me</a></li>
                    <li><a href="project">Project</a></li>
                    <li><a href="matkul_create">Tambah Matkul</a></li>
                    <li><a href="list">List Matkul</a></li>

                    {% elif request.get_full_path == "/about" %}
                    <li><a href="/">Home</a></li>
                    <li class="active"><a href="about">About Me</a></li>
                    <li><a href="project">Project</a></li>
                    <li><a href="matkul_create">Tambah Matkul</a></li>
                    <li><a href="list">List Matkul</a></li>

                    {% elif request.get_full_path == "/project" %}
                    <li><a href="/">Home</a></li>
                    <li><a href="about">About Me</a></li>
                    <li class="active"><a href="project">Project</a></li>
                    <li><a href="matkul_create">Tambah Matkul</a></li>
                    <li><a href="list">List Matkul</a></li>

                    {% elif request.get_full_path == "/matkul_create" %}
                    <li><a href="/">Home</a></li>
                    <li><a href="about">About Me</a></li>
                    <li><a href="project">Project</a></li>
                    <li class="active"><a href="matkul_create">Tambah Matkul</a></li>
                    <li><a href="list">List Matkul</a></li>

                    {% elif request.get_full_path == "/list" %}
                    <li><a href="/">Home</a></li>
                    <li><a href="about">About Me</a></li>
                    <li><a href="project">Project</a></li>
                    <li><a href="matkul_create">Tambah Matkul</a></li>
                    <li class="active"><a href="list">List Matkul</a></li>

                    {% else %}
                    <li><a href="/">Home</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <div class="profile-main">
        {% block content %}
        {% endblock content %}
        <div class="footer">
            <p><strong>Contact me:</strong></p><br>
            <div class="footer-box"><a href="https://www.facebook.com/brian.christian.39/"><i class="fa fa-facebook"></i></a></div>
            <div class="footer-box"><a href="https://twitter.com/Brian_1801"><i class="fa fa-twitter"></i></a></div>
            <div class="footer-box"><a href="https://steamcommunity.com/profiles/76561198175372785"><i class="fa fa-steam"></i></a></div>
        </div>
    </div>
</body>
</html>

home/templates/home/about.html
<!DOCTYPE html>
<html lang="en">
<link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">

{% extends 'base.html' %}
{% load static %}

<head>
  {% block meta %}
  <title>About Me</title>
  {% endblock meta %}
</head>

<body>
  {% block content %}
    <div class="profile-header">
      <div class="self-detail">
        <div class="self-image">
          <img src="/static/images/Pasfoto.jpg">
        </div>
        <div class="self-data">
          <h2>Brian Christian</h2>
          <p>1906398295</p>
          <p>Student at <strong>Universitas Indonesia</strong><br>
            <i class="fa fa-map-marker" aria-hidden="true"></i>  Jakarta, Indonesia
          </p>
        </div>
      </div>
      <div class="tab-panel-main">
        <ul class="tabs">
          <li class="tab-link current" data-tab="Basic-info">Basic Info</li>
          <li class="tab-link" data-tab="Edu-info">Education History</li>
          <li class="tab-link" data-tab="Exp-info">Experience</li>
        </ul>
        <div id="Basic-info" class="tab-content current">
          <div class="profile-box">
            <div class="heading">
              <p>Profile</p>
            </div>
            <div class="desc">
              I am a student of class 2019 currently studying at the Faculty of Computer Science, 
              Universitas Indonesia. I like things related to technology, especially in the field 
              of computer science. Outside of that, I have an interest in music, gaming, and reading.
            </div>
          </div>
          <div class="detail-box">
            <p>Detail</p>
            <ul class="ul-first">
              <li>Birth date</li>
              <li>City</li>
              <li>Country</li>
              <li>Contact</li>
            </ul>
            <ul class="ul-second">
              <li>18 January 2002</li>
              <li>Jakarta</li>
              <li>Indonesia</li>
              <li>brian.christian@ui.ac.id</li>
            </ul>
          </div>
        </div>
        <div id="Edu-info" class="tab-content">
          <div class="Edu-box-main">
            <h2><i class="fa fa-graduation-cap" aria-hidden="true"></i> Education</h2>
            <div class="Edu-box">
              <h5><span>SD Budhaya II</span> <br>
                2007 - 2013 | </h5>
            </div>
            <div class="Edu-box">
              <h5><span>SMPK 5 Penabur</span> <br>
                2013 - 2016 | </h5>
            </div>
            <div class="Edu-box">
              <h5><span>SMAK 7 Penabur</span> <br>
                2016 - 2019 | Science</h5>
            </div>
            <div class="Edu-box">
              <h5><span>Universitas Indonesia</span> <br>
                2019 - Now | Computer Science</h5>
            </div>
          </div>
        </div>
        <div id="Exp-info" class="tab-content">
          <div class="Exp-box">
            <h3>Skills</h3>
            <div class="skill-box"><img src="/static/images/python.svg"></div>
            <div class="skill-box"><img src="/static/images/java.svg"></div>
            <div class="skill-box"><img src="/static/images/Bootstrap_logo.svg"></div>
            <div class="skill-box"><img src="/static/images/html-5.svg"></div>
            <div class="skill-box"><img src="/static/images/css-3.svg"></div>
            <div class="skill-box"><img src="/static/images/flask.png"></div>
          </div>
        </div>
      </div>
    </div>
    <div style="clear: both;"></div>

  <script type="text/javascript">
    $(document).ready(function () {
      $('ul.tabs li').click(function () {
        var tab_id = $(this).attr('data-tab');

        $('ul.tabs li').removeClass('current');
        $('.tab-content').removeClass('current');

        $(this).addClass('current');
        $("#" + tab_id).addClass('current');
      });
    });
  </script>
  {% endblock content %}
</body>
</html>

home/templates/home/delete.html
{% extends 'base.html' %}

{% block meta %}
<title>Delete Matkul</title>
{% endblock meta %}

{% block content %}
<div class="delete-matkul">
    <h1>Delete Matkul</h1>
    <br/>
    <h3>Delete: {{ matkul.NamaMatkul }}</h3>
    <div class="form-group">
        <form method="POST"> {% csrf_token %}
            <strong>Yakin???</strong>
            <br/>
            <button class="tombol">
                <p>Delete Matkul!</p>
            </button>
        </form>
    </div>
</div>
{% endblock content %}

home/templates/home/detail.html
{% extends 'base.html' %}

{% block meta %}
<title>Detail Matkul</title>
{% endblock meta %}

{% block content %}
<div class="box-matkul">
    <h1>{{ matkul.NamaMatkul }}</h1>
    <p>Dosen      : {{ matkul.Dosen }}</p>
    <p>Jumlah sks : {{ matkul.sks }}</p>
    <p>Deskripsi  : {{ matkul.deskripsi }}</p>
    <p>Semester   : {{ matkul.smst }}</p>
    <p>Ruang Kelas: {{ matkul.kelas }}</p>
    <div class="back-tag">
        <a href="../list">
        <p>Back -></p>
        </a>
    </div>
</div>
{% endblock content %}

home/templates/home/index.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}
{% load static %}

<head>
  {% block meta %}
  <title>Welcome!</title>
  {% endblock meta %}
</head>

<body>
  {% block content %}
    <div class="profile-content">
      <div class="profile-image">
        <img src="/static/images/Foto.jpg">
      </div>
      <div class="profile-data">
        <h1>Hi! I'm Brian</h1>
        <div class="about-tag"><a href="about">
          <p>About Me -></p>
        </a>
        </div>
      </div>
    </div>
    <div style="clear: both;"></div>
  {% endblock content %}
</body>
</html>

home/templates/home/matkul_create.html
{% extends 'base.html' %}

{% block meta %}
<title>Tambah Matkul</title>
{% endblock meta %}


{% block content %}
<div class="form-matkul">
    <h1>Tambah Mata Kuliah</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        <input type='submit' class='button' value='Submit' />
    </form>
</div>
{% endblock content %}

home/templates/home/matkul_list.html
{% extends 'base.html' %}

{% block meta %}
<title>List Matkul</title>
{% endblock meta %}

{% block content %}
<div class="box-matkuls">
    <h1>Mata Kuliyah</h1>
    <ul>
        {% for matkul in object_list %}
        <li><a href="{% url 'home:detail' matkul.pk  %}">{{ matkul.NamaMatkul }}</a><br/></li>
        <small><a href="{% url 'home:delete' matkul.pk  %}">(Delete)</a></small>
        {% endfor %}
    </ul>
</div>
{% endblock content %}

home/templates/home/project.html
<!DOCTYPE html>
<html lang="en">

{% extends 'base.html' %}
{% load static %}

<head>
  {% block meta %}
  <title>Projects</title>
  {% endblock meta %}
</head>

<body>
  {% block content %}
    <div class="profile-project">
      <h4>Projects</h4>
      <div class="projects">
        <div class="projects-image">
          <img src="/static/images/WIP.jpg">
          <p>Lorem ipsum dolor sit amet</p>
        </div>
      </div>
      <div class="projects">
        <div class="projects-image">
          <img src="/static/images/WIP.jpg">
          <p>Lorem ipsum dolor sit amet</p>
        </div>
      </div>
      <div class="projects">
        <div class="projects-image">
          <img src="/static/images/WIP.jpg">
          <p>Lorem ipsum dolor sit amet</p>
        </div>
      </div>
      <div class="projects">
        <div class="projects-image">
          <img src="/static/images/WIP.jpg">
          <p>Lorem ipsum dolor sit amet</p>
        </div>
      </div>
    </div>
    <div style="clear: both;"></div>
  {% endblock content %}
</body>
</html>